### ISSUE TITLE
Refresh grub2 config after removing kernels

### ISSUE THREAD

**Issue by stannicek** [mgorny/eclean-kernel2#10]
Hello.

It would be great to refresh grub2 config file automaticaly, so that removed kernels are cleaned also from grub2 config file.

Regards,
Stanislav

**Comment by mgorny** [comment]
There is a plan to add a whole bootloader support infrastructure but I don't know when I'll have time to work on this.

**Comment by mgorny** [comment]
Actually, grub2 support is already present in current git HEAD. I'd prefer if someone with grub2 installed tested it before I made the next release.

**Comment by mgorny** [comment]
Released in 1.99.4
