### ISSUE TITLE
Feature: sys-boot/syslinux support

### ISSUE THREAD

**Issue by nado** [mgorny/eclean-kernel2#6]
Hi,

Would you consider supporting syslinux as bootloader ?

**Comment by mgorny** [comment]
At some point, surely yes. But I need more information about it. For a start, whether it's manually configured like LILO/ol' GRUB or autogenerated like GRUB2, and an example config file pasted here.

**Comment by nado** [comment]
Actually I ended up rewriting my installkernel script to overwrite previous binary of the kernel, thus I don't need the check in /boot anymore.

If eclean-kernel could just check for files in /usr/src and /lib/modules it would be enough to me, otherwise I could hack into the post/pre merge/unmerge hooks for the kernel.
```
UI menu.c32
PROMPT 0
  
MENU TITLE Boot Menu
TIMEOUT 5
DEFAULT gentoo

LABEL gentoo
	MENU LABEL Gentoo
	KERNEL /boot/linux
	APPEND ro root=/dev/sda1 quiet net.ifnames=0

LABEL fallback
	MENU LABEL Gentoo Fallback
	KERNEL /boot/fallback
	APPEND ro root=/dev/sda1 net.ifnames=0

LABEL memtest
	MENU LABEL Memtest86+
	LINUX /boot/memtest86plus/memtest.bin
```

**Comment by mgorny** [comment]
If you mean removing /lib/modules for kernels that were removed, then just pass `-n 9999` or alike.

**Comment by nado** [comment]
Ok, thank you, I am closing this since the features asked are either useless now or already implemented.
.
