### ISSUE TITLE
sorting is not correct, should use natural sort instead of lexical

### ISSUE THREAD

**Issue by mpkh** [mgorny/eclean-kernel2#8]

**Comment by evsh** [comment]
Probably related:
`# ls /boot/
System.map-4.8.11-gentoo  config-4.8.11-gentoo  efi   initramfs-4.8.11-gentoo.img  lost+found     refind_linux.conf      vmlinuz-4.8.8-gentoo
System.map-4.8.8-gentoo   config-4.8.8-gentoo   grub  initramfs-4.8.8-gentoo.img   memtest86plus  vmlinuz-4.8.11-gentoo
`
but:
`# eclean-kernel -p -n 1
The following kernels would be removed:
4.8.11-gentoo:
`

**Comment by mpkh** [comment]
@evsh yes still looks like problem of this functionhttps://github.com/mpkh/eclean-kernel2/blob/bf266226509abb2e6ca1302e276da960ccbf2de3/src/ek2/sorts.cxx#L101-L113

8 and 1 (2 (len of 11) - 1 (minimal len)) comes to function, 8 != 0 >> return true >> 8 > 11

**Comment by mgorny** [comment]
This should be fixed wrt #9.
